theme = "theme"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
true-color = true
gutters = [ "line-numbers", "spacer" ]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
"A-[" = "goto_previous_buffer"
"A-]" = "goto_next_buffer"
A-x = "extend_to_line_bounds"
X = "select_line_above"

[keys.select]
A-x = "extend_to_line_bounds"
X = "select_line_above"
